---
driver:
  name: docker
  use_sudo: false

verifier:
  name: inspec

provisioner:
  name: shell

platforms:
  - name: debian
  - name: debian-9
    driver_config:
      name: vagrant

suites:
  - name: default
  - name: server
    provisioner:
      script: "server.sh"
